version: '3.7'

services:
  auto-crud:
    image: golang:1.21rc2-alpine3.18
    container_name: auto-crud
    working_dir: /app
    volumes:
      - $PWD:/app
    ports:
      - 9055:9055
    entrypoint: tail -f /dev/null